site_name: JustinWritesCode Technical Documentation
site_description: JustinWritesCode Technical Documentation
site_url: https://justinwritescode.com
site_author: "Justin Chase"
repo_url: https://github.com/justinwritescode/justinwritescode.git
repo_name: justinwritescode/justinwritescode
edit_uri: ""
docs_dir: docs
theme:
  name: material
  icon:
    logo: material/human-male-male
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    scheme: slate
    primary: teal
    accent: blue
features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - toc.integrate
  - search.suggest
  - search.highlighting
  - search.share
  - announce.dismiss
plugins:
  - rss
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
extra:
  homepage: https://justinwritescode.com
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/justhorny32
      name: Justin Chase on Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/justhorny32
      name: Justin Chase on Telegram
  version:
    provider: mike
copyright: Copyright &copy; 2022 Justin Chase
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - abbr
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.details
  - footnotes
  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3
  - tables
  - md_in_html
  - attr_list
  - admonition
  - abbr
nav:
  - Home: index.md
  - About: README.md
  - Documentation:
      - docs/index.md
      - nuget-icons: '!import {https://github.com/justinwritescode/nuget-icons}?branch=main&docs_dir=docs&multi_docs=true&config=mkdocs.yml'
  - Code of Conduct: CODE_OF_CONDUCT.md
  - License: LICENSE
  - Privacy Policy: PRIVACY_POLICY.md
  - Tags: tags.md
