# This workflow builds and deploys an mkdocs site to GitHub Pages
name: gh-pages cd

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push dir to Git
        # You may pin to the exact commit or the version.
        # uses: liziwl/git-push-action@abc14cffc5cecdb80f1bebe86becab5aca602a75
        uses: liziwl/git-push-action@v1.0.4
        with:
          # Username of token holder
          git_token_holder: justinwritescode
          # Token for the destination repo. Can be passed in using $\{{ secrets.GIT_TOKEN }}
          git_token: ${{ secrets.REPO_TOKEN }}
          # Repository URL after "https://", like "github.com/USER_NAME/REPO_NAME.git"
          repository_url: https://github.com/justinwritescode/docs.git
          # Directory to push
          push_dir: docs
          # User to commit
          commit_user: justinwritescode
          # Email of the user to commit
          commit_email: justin@justinwritescode.com
          # Destination branch to push changes
          branch: main # optional, default is master
          # Keep commit history
          keep_history: true # optional
          # Commit messgae
          commit_message: "CI for GH Pages" # optional
